dahliainthecity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('about/', views.about, name='about'),
  path('places/', views.places_index, name='places_index'),
  path('places/<int:place_id>/', views.places_detail, name='places_detail'),
  path('places/create/', views.PlaceCreate.as_view(), name='places_create'),
  path('places/<int:pk>/update/', views.PlaceUpdate.as_view(), name='places_update'),
  path('places/<int:pk>/delete/', views.PlaceDelete.as_view(), name='places_delete'),
  path('places/<int:place_id>/add_visit/', views.add_visit, name='add_visit'),
  path('places/<int:place_id>/add_todo/', views.add_todo, name='add_todo'),
  path('accounts/signup/', views.signup, name='signup'),

]

main_app/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

VISITED = (
  ('1', 'Visited'),
  ('2', 'Not Visited'),
)

# Create your models here.
class Place(models.Model):
  name = models.CharField(max_length=100)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('places_detail', kwargs={'place_id': self.id})

class Visit(models.Model):
  date = models.DateField()
  visited = models.CharField(
    max_length=1,
    choices=VISITED,
    default=VISITED[0][0]
  )
  place = models.ForeignKey(Place, on_delete=models.CASCADE)
  def __str__(self):
    return f"{self.get_visited_display()} on {self.date}"

  class Meta:
    ordering = ['-date']

class Doing(models.Model):
  todo = models.CharField(max_length=100)
  complete = models.BooleanField(default=False)

  place = models.ForeignKey(Place, on_delete=models.CASCADE)
  def __str__(self):
    return self.todo
  

main_app/forms.py
from django.forms import ModelForm
from .models import Visit, Doing


class VisitForm(ModelForm):
  class Meta:
    model = Visit
    fields = ['date', 'visited']

class DoingForm(ModelForm):
  class Meta:
    model = Doing
    fields = ['todo', 'complete']

main_app/views.py
from unicodedata import name
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Place
from .forms import VisitForm, DoingForm
from django.http import HttpResponse
from django.contrib.auth.views import LoginView

# Create your views here.
class Home(LoginView):
  template_name = 'home.html'

def about(request):
  return render(request, 'about.html')

@login_required
def places_index(request):
  places = Place.objects.filter(user=request.user)
  return render(request, 'places/index.html', { 'places': places })

@login_required
def places_detail(request, place_id):
  place = Place.objects.get(id=place_id)
  visiting_form = VisitForm()
  todo_form = DoingForm()
  # todo_list = DoingForm.objects.order_by('id')
  return render(request, 'places/detail.html', { 
    'place': place, 'visiting_form': visiting_form, 'todo_form': todo_form
  })
  

@login_required
def add_visit(request, place_id):
  form = VisitForm(request.POST)
  if form.is_valid():
    new_visit = form.save(commit=False)
    new_visit.place_id = place_id
    new_visit.save()
  return redirect('places_detail', place_id=place_id)

@login_required
def add_todo(request, place_id):
  form = DoingForm(request.POST)
  if form.is_valid():
    new_todo = form.save(commit=False)
    new_todo.place_id = place_id
    new_todo.save()
  return redirect('places_detail', place_id=place_id)

class PlaceCreate(LoginRequiredMixin, CreateView):
  model = Place
  fields = ['name']
  success_url = '/places/'
  def form_valid(self, form):
    form.instance.user = self.request.user 
    return super().form_valid(form)

class PlaceUpdate(LoginRequiredMixin, UpdateView):
  model = Place
  fields = ['name']

class PlaceDelete(LoginRequiredMixin, DeleteView):
  model = Place
  success_url = '/places/'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('places_index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
  <h1>About Dahlia In The City</h1>
  <hr />
<p class="page-content">
  Dahlia In the city is an app to track and document the places I want to see and the things I want to do when I am there.
</p>

{% endblock %}
</body>
</html>

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
    rel="shortcut icon"
    type="image/png"
    href="{% static 'images/favicon.png' %}"
  >
  <title>Dahlia In The City</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
    <div class="header-logo-container">
      <a href="/">
        <img class="tinypic" src="{% static 'images/inthe.png' %}" alt="City Scape" />
      </a>
    </div>
    <nav>
      <ul>
        {% if user.is_authenticated %}
          <li><a href="/places">All Places</a></li>
          <li><a href="{% url 'places_create' %}">Add a Place</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="{% url 'logout' %}">Log out</a></li>
        {% else %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block content %}

<section class="logo-container">
  <img class="tiny" src="{% static 'images/inthe.png' %}" alt="in the city logo" />
</section>
{% if not user.is_authenticated %}
<section>
  <form action="{% url 'home' %}" method="post" class="login">
    <h1>Login</h1>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next }}">
    <button type="submit" class="btn submit">Login</button>
  </form>
</section>
{% endif %}



{% endblock %}

main_app/templates/main_app/place_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Place?</h1>
  <img src="{% static 'images/sad.png' %}" alt="A sad face"/>
</div>
<h2>Are you sure you want to delete {{ place.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'places_detail' place.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/place_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}


<div class="page-header">
  {% if object %}
  <h1>Edit {{place.name}}</h1>
  {% else %}
  <h1>Add a Place</h1>
  {% endif %}
</div>
{% comment %} 

{% endcomment %}
<form action="" method="post" class="form-container">
  {% comment %} 

  {% endcomment %}
  {% csrf_token %}
  <table>
    {% comment %}

    {% endcomment %}
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/places/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  href="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.css" 
  rel="stylesheet" 
/>
<link rel="stylesheet" href="{% static 'css/mcdp.css' %}">
<script 
  src="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.js"
>
</script>
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/places/place-detail.css' %}"
/>
<script defer src="{% static 'js/place-detail.js' %}"></script>
{% endblock %}

{% block content %}

<section class="place-container">
  <div class="place-img">
    <img 
      src="{% static 'images/todo.gif' %}" 
      alt="TODO"
    >
  </div>
  <div class="todos-container">
    <section class="todos">
      <div class="subsection-title">
        <h1>Things to do in {{ place.name }}!!</h1>
      </div>
      <table>
        <thead>
          <tr><th>
            <form
            action="{% url 'add_todo' place.id %}" 
            method="post" 
            class="subsection-content"
          >
            {% csrf_token %}
            {{ todo_form.as_p }}
            <br>
            <button type="submit" class="btn submit">Add</button>
          </form>

            </form>
          </th></tr>
        </thead>
        <tbody>
          {% for doing in place.doing_set.all %}
            <tr>
              {% if doing.complete %}
                <td>✔️{{doing.todo}}</td>
                {% comment %} <td>✔️{{doing.get_todo_display}}</td> {% endcomment %}
              {% else %}
                <td>{{doing.todo}}</td>
                {% comment %} <td>{{doing.get_todo_display}}</td> {% endcomment %}
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </section>   
  </div>
</section>
<div class="visits-container">
  <section class="visits">
    <div class="subsection-title">
      <h2>Visits</h2>
      <img 
        src="{% static 'images/happy.png' %}" 
        alt="Happy"
      />
    </div>
    <h3>Add a Visit</h3>
    <form
      action="{% url 'add_visit' place.id %}" 
      method="post" 
      class="subsection-content"
    >
      {% csrf_token %}
      {{ visiting_form.as_p }}
      <button type="submit" class="btn">Add</button>
    </form>
    <h3>Past Visits</h3>
    {% if place.visit_set.all.count %}
    <table>
      <thead>
        <tr><th>Date</th><th>Visit</th></tr>
      </thead>
      <tbody>
        {% for visit in place.visit_set.all %}
          <tr>
            <td>{{visit.date}}</td>
            <td>{{visit.get_visited_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
			<div class="subsection-content">
        <p>Buy a plane ticket to {{place.name}}!!!</p>
      </div>
    {% endif %}
  </section>
</div>

<div class="button-actions">
  <a href="{% url 'places_update' place.id %}" class="btn warn">Edit</a>
  <a href="{% url 'places_delete' place.id %}" class="btn danger">Delete</a>
</div>

{% endblock %}

main_app/templates/places/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/places/place-index.css' %}"
/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>Places To See</h1>
  <img src="{% static 'images/eyes.png' %}" alt="A boarding pass" />
</section>

<section class="card-container">
  <div class="card">
    {% for place in places %}
    <a href="{% url 'places_detail' place.id %}">
      <div class="card-content">
      <div class="card-img-container">
      </div>
      <h2 class="card-title">{{ place.name }}</h2>
    </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/happy.png' %}" alt="A happy face"/>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}